Repository datarevenue-berlin/omigami, pull requests merged in 2021-01, with the labels that each got.

#16 OM-29 Add get item to SelectedFeatures
  notebooks/MinimalExample.ipynb
  omigami/__init__.py
  omigami/data_structures/data_models.py
  omigami/feature_selector.py
  omigami/permutation_test.py
  omigami/plot_utils.py
  omigami/post_processor.py
  tests/test_data_models.py
  tests/test_feature_selector.py
  tests/test_permutation_test.py
  tests/test_post_processor.py
Labels: next-release

#19 Split axis in box plot
  omigami/plot_utils.py
Labels: next-release

#17 Set up CI with Azure Pipelines
  azure-pipelines.yml
Labels: next-release

#20 Om 31 wrap plsregressor or it would break the pipeline
  omigami/models/__init__.py
  omigami/models/pls.py
  omigami/permutation_test.py
  tests/test_estimator.py
  tests/test_pls.py
  tests/test_utils.py
Labels: bug, next-release

#23 Giulio/fix setup readme
  README.md
  setup.py
Labels: bug
